# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-16 14:58
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(help_text='请输入小于200字符的描述！', max_length=250, verbose_name='评论信息')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='会员账号')),
            ],
        ),
    ]
