# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-16 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='CommentSet',
        ),
    ]
