# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-16 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_auto_20181016_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentset',
            options={'verbose_name': '网站评论', 'verbose_name_plural': '网站评论'},
        ),
    ]
