# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-16 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_auto_20181016_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentset',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserSetting', verbose_name='会员账号'),
        ),
    ]
