# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-16 15:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0008_auto_20181016_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentset',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='会员账号'),
        ),
    ]
