# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-16 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0009_auto_20181016_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentset',
            name='good',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='点赞数量'),
        ),
    ]
