# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-11 14:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guanggao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='请输入小于200字符的描述！', max_length=250, verbose_name='广告名字')),
                ('image', models.ImageField(blank=True, null=True, upload_to='zl955/abb/', verbose_name='广告图片')),
                ('href', models.CharField(help_text='请输入小于200字符的描述！', max_length=250, verbose_name='广告图片跳转链接')),
                ('is_show', models.BooleanField(default=False)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '广告设置',
                'verbose_name_plural': '广告设置',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='请输入小于200字符的描述！', max_length=250, verbose_name='网站标题')),
                ('keywords', models.CharField(help_text='请输入小于200字符的描述！', max_length=250, verbose_name='网站关键词 - seo')),
                ('description', models.CharField(help_text='请输入小于200字符的描述！', max_length=250, verbose_name='网站介绍词 - seo')),
                ('icons', models.ImageField(blank=True, null=True, upload_to='zl955/setting/', verbose_name='favicon图标')),
                ('logo_pic', models.ImageField(blank=True, null=True, upload_to='zl955/setting/', verbose_name='网站标题图片')),
                ('water_pic', models.ImageField(blank=True, null=True, upload_to='zl955/setting/', verbose_name='水印背景图片上传')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '网站设置',
                'verbose_name_plural': '网站设置',
            },
        ),
    ]
