# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-11 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zl955', '0002_auto_20181011_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guanggao',
            name='is_show',
            field=models.BooleanField(choices=[(False, '不显示'), (True, '显示')], default=True, max_length=2, verbose_name='是否显示'),
        ),
    ]
