# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-11 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zl955', '0004_auto_20181011_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guanggao',
            name='href',
            field=models.CharField(help_text='请输入小于200字符的描述！', max_length=250, verbose_name='广告链接'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='description',
            field=models.CharField(help_text='请输入小于200字符的描述！', max_length=250, verbose_name='SEO-网站介绍词'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='keywords',
            field=models.CharField(help_text='请输入小于200字符的描述！', max_length=250, verbose_name='SEO-网站关键词'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='water_pic',
            field=models.ImageField(blank=True, null=True, upload_to='zl955/setting/', verbose_name='水印背景图片'),
        ),
    ]
