# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-11 15:21
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zl955', '0005_auto_20181011_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(help_text='请输入小于50字符的描述！', max_length=55, verbose_name='开奖期号')),
                ('no1', models.CharField(blank=True, help_text='请输第1位号码！', max_length=55, null=True, verbose_name='第1位')),
                ('no2', models.CharField(blank=True, help_text='请输第2位号码！', max_length=55, null=True, verbose_name='第2位')),
                ('no3', models.CharField(blank=True, help_text='请输第3位号码！', max_length=55, null=True, verbose_name='第3位')),
                ('no4', models.CharField(blank=True, help_text='请输第4位号码！', max_length=55, null=True, verbose_name='第4位')),
                ('no5', models.CharField(blank=True, help_text='请输第5位号码！', max_length=55, null=True, verbose_name='第5位')),
                ('no6', models.CharField(blank=True, help_text='请输第6位号码！', max_length=55, null=True, verbose_name='第6位')),
                ('no7', models.CharField(blank=True, help_text='请输第7位号码！', max_length=55, null=True, verbose_name='第7位')),
                ('info', DjangoUeditor.models.UEditorField(default='', verbose_name='详细信息')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '最新开奖',
                'verbose_name_plural': '最新开奖',
            },
        ),
    ]
