# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-11 15:45
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zl955', '0007_auto_20181011_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Open',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(help_text='请输入小于50字符的描述！', max_length=55, verbose_name='期号')),
                ('top', models.CharField(help_text='请输入小于200字符的描述！', max_length=250, verbose_name='开头文字简述')),
                ('desc', DjangoUeditor.models.UEditorField(default='', verbose_name='详细信息')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '开奖',
                'verbose_name_plural': '开奖',
            },
        ),
        migrations.RenameField(
            model_name='opennew',
            old_name='info',
            new_name='desc',
        ),
    ]
