# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-11 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zl955', '0008_auto_20181011_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='open',
            options={'verbose_name': '新增开奖', 'verbose_name_plural': '新增开奖'},
        ),
    ]
