# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-11 15:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zl955', '0010_bottoms'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiaoChuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leftt', models.ImageField(blank=True, null=True, upload_to='zl955/float/', verbose_name='左飘窗')),
                ('leftt_herf', models.CharField(help_text='请输入小于200字符的描述！', max_length=250, verbose_name='左飘窗链接')),
                ('rightt', models.ImageField(blank=True, null=True, upload_to='zl955/float/', verbose_name='右飘窗')),
                ('rightt_herf', models.CharField(help_text='请输入小于200字符的描述！', max_length=250, verbose_name='右飘窗链接')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '左右飘窗',
                'verbose_name_plural': '左右飘窗',
            },
        ),
    ]
