# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-11 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zl955', '0013_auto_20181011_1647'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ipapp',
            unique_together=set([]),
        ),
    ]
