# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-11 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zl955', '0014_auto_20181011_1649'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ipapp',
            unique_together=set([('ip',)]),
        ),
    ]
