# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-12 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zl955', '0015_auto_20181011_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='open_limit',
            field=models.IntegerField(default=5, verbose_name='开奖显示条数'),
        ),
    ]
