# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-12 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zl955', '0017_bottoms_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='piaochuan',
            name='name',
            field=models.CharField(default=0, help_text='请输入小于200字符的描述！', max_length=250, verbose_name='左右飘窗'),
            preserve_default=False,
        ),
    ]
