# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-12 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zl955', '0018_piaochuan_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='open_limit',
        ),
    ]
