# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-12 21:23
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zl955', '0021_auto_20181012_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='open',
            name='desc',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='详细信息'),
        ),
    ]
