# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-14 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reg_ip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='注册IP'),
        ),
    ]
