# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-14 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181014_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reg_ip',
            new_name='ip',
        ),
    ]
