# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-16 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20181014_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='users/avatar/default.png', upload_to='users/avatar/%Y/%m'),
        ),
    ]
