# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-16 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.UserSetting', verbose_name='会员组'),
            preserve_default=False,
        ),
    ]
