# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-16 18:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='请输入小于200字符的描述！', max_length=250, verbose_name='代理信息')),
                ('urls', models.CharField(help_text='请输入小于200字符的描述！', max_length=250, verbose_name='代理地址')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '代理信息',
                'verbose_name_plural': '代理信息',
            },
        ),
        migrations.CreateModel(
            name='HotApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='请输入小于200字符的描述！', max_length=250, null=True, verbose_name='活动名称')),
                ('urls', models.CharField(blank=True, help_text='请输入小于200字符的描述！', max_length=250, null=True, verbose_name='活动跳转地址')),
                ('images', models.ImageField(blank=True, null=True, upload_to='hot/images/', verbose_name='活动图片')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '活动图片',
                'verbose_name_plural': '活动图片',
            },
        ),
        migrations.CreateModel(
            name='HtmlApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='请输入小于200字符的描述！', max_length=250, verbose_name='网站标题')),
                ('icons', models.ImageField(blank=True, null=True, upload_to='icons/images/', verbose_name='favicon图标')),
                ('keywords', models.CharField(help_text='请输入小于200字符的描述！', max_length=250, verbose_name='网站关键词 - 有助于SEO推广')),
                ('description', models.CharField(help_text='请输入小于200字符的描述！', max_length=250, verbose_name='网站表述 - 有助于SEO推广')),
                ('service', models.CharField(help_text='请输入小于200字符的描述！', max_length=250, verbose_name='客服地址')),
                ('top', models.ImageField(blank=True, null=True, upload_to='top/images/', verbose_name='顶部图片')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '代理页面',
                'verbose_name_plural': '代理页面',
            },
        ),
        migrations.CreateModel(
            name='IpsApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='请输入小于200字符的描述！', max_length=250, null=True, verbose_name='地址描述')),
                ('ips', models.CharField(max_length=250, verbose_name='IP地址')),
                ('no', models.IntegerField(blank=True, null=True, verbose_name='访问次数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '获取IP',
                'verbose_name_plural': '获取IP',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ipsapp',
            unique_together=set([('ips',)]),
        ),
    ]
